USE [master]
GO

/****** Object:  Database [TradingSystem]    Script Date: 2022/10/19 15:58:32 ******/
CREATE DATABASE [TradingSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TradingSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TradingSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TradingSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TradingSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TradingSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TradingSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TradingSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TradingSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TradingSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TradingSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [TradingSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TradingSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TradingSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TradingSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TradingSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TradingSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TradingSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TradingSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TradingSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TradingSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TradingSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TradingSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TradingSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TradingSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TradingSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TradingSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TradingSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TradingSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [TradingSystem] SET  MULTI_USER 
GO

ALTER DATABASE [TradingSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TradingSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TradingSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TradingSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TradingSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TradingSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TradingSystem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TradingSystem] SET  READ_WRITE 
GO

